# Hometask: Pandas

In [2]:
import pandas as pd 
import numpy as np

# Question 1

In [ ]:
def answer_one():
    energy = pd.read_excel('Energy Indicators.xls', skiprows=17, skipfooter=38)
    energy = energy.drop(energy.columns[[0, 1]], axis=1)
    energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
    energy.replace('...', np.nan, inplace=True)
    energy['Energy Supply'] *= 1000000
    
    energy['Country'] = energy['Country'].str.replace(r"\d+", "", regex=True).str.replace(r"\(.*\)", "", regex=True).str.strip()
    energy['Country'] = energy['Country'].replace({
        "Republic of Korea": "South Korea", "United States of America": "United States",
        "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
        "China, Hong Kong Special Administrative Region": "Hong Kong"
    })

    # ВВП 
    gdp = pd.read_excel('world_bank.xls', sheet_name='Data', skiprows=3)
    
    gdp.rename(columns={gdp.columns[0]: 'Country'}, inplace=True)
    
    relevant_cols = ['Country']
    years_mapping = {} 
    
    target_range = range(2006, 2016)
    
    for col in gdp.columns:
        try:
            val = int(float(col))
            if val in target_range:
                relevant_cols.append(col)
                years_mapping[col] = str(val)
        except:
            continue
            
    gdp = gdp[relevant_cols]
    gdp.rename(columns=years_mapping, inplace=True)
    
    gdp['Country'] = gdp['Country'].replace({
        "Korea, Rep.": "South Korea", "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"
    })

    # ScimEn 
    scimen = pd.read_excel('scimagojr.xlsx')
    scimen_top15 = scimen[:15]

    # Об'єднання
    df = pd.merge(scimen_top15, energy, how='inner', on='Country')
    df = pd.merge(df, gdp, how='inner', on='Country')
    
    df.set_index('Country', inplace=True)
    
    final_years = [str(y) for y in target_range]
    df[final_years] = df[final_years].apply(pd.to_numeric, errors='coerce')
    
    return df

In [ ]:
Top15 = answer_one()
Top15

,Rank,Region,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,,
China,1,Asiatic Region,273437,272374,2336764,1615239,8.55,245,127191000000,93,...,2.752119e+12,3.550328e+12,4.594337e+12,5.101691e+12,6.087192e+12,7.551545e+12,8.532186e+12,9.570471e+12,1.047562e+13,1.106157e+13
United States,2,Northern America,175891,172431,2230544,724472,12.68,363,90838000000,286,...,1.381559e+13,1.447423e+13,1.476986e+13,1.447806e+13,1.504896e+13,1.559973e+13,1.625397e+13,1.684319e+13,1.755068e+13,1.820602e+13
India,3,Asiatic Region,55082,53775,463165,162944,8.41,181,33195000000,26,...,9.402599e+11,1.216736e+12,1.198895e+12,1.341888e+12,1.675616e+12,1.823052e+12,1.827638e+12,1.856721e+12,2.039126e+12,2.103588e+12
Japan,4,Asiatic Region,50523,50065,488062,119930,9.66,193,18984000000,149,...,4.601663e+12,4.579750e+12,5.106679e+12,5.289494e+12,5.759072e+12,6.233147e+12,6.272363e+12,5.212328e+12,4.896994e+12,4.444931e+12
United Kingdom,5,Western Europe,43389,42284,615670,111290,14.19,226,7920000000,124,...,2.709978e+12,3.092996e+12,2.931684e+12,2.417566e+12,2.491397e+12,2.666403e+12,2.706341e+12,2.786315e+12,3.065223e+12,2.934858e+12
Germany,6,Western Europe,38739,38013,433148,95145,11.18,196,13261000000,165,...,2.994704e+12,3.425578e+12,3.745264e+12,3.411261e+12,3.399668e+12,3.749315e+12,3.527143e+12,3.733805e+12,3.889093e+12,3.357586e+12
Russian Federation,7,Eastern Europe,36735,36560,115938,54993,3.16,90,30709000000,214,...,9.899321e+11,1.299703e+12,1.660848e+12,1.222646e+12,1.524917e+12,2.045923e+12,2.208294e+12,2.292470e+12,2.059242e+12,1.363482e+12
Canada,8,Northern America,33472,32863,568080,100953,16.97,227,10431000000,296,...,1.319265e+12,1.468820e+12,1.552990e+12,1.374625e+12,1.617343e+12,1.793327e+12,1.828366e+12,1.846597e+12,1.805750e+12,1.556509e+12
Italy,9,Western Europe,27983,26940,352993,87828,12.61,166,6530000000,109,...,1.949552e+12,2.213102e+12,2.408655e+12,2.199929e+12,2.136100e+12,2.294994e+12,2.086958e+12,2.141924e+12,2.162010e+12,1.836638e+12
South Korea,10,Asiatic Region,27655,27445,328488,61531,11.88,155,11007000000,221,...,1.053217e+12,1.172614e+12,1.047339e+12,9.439419e+11,1.144067e+12,1.253223e+12,1.278428e+12,1.370795e+12,1.484318e+12,1.465773e+12
France,11,Western Europe,25232,24732,343860,65734,13.63,178,10597000000,166,...,2.320536e+12,2.660591e+12,2.930304e+12,2.700887e+12,2.645188e+12,2.865158e+12,2.683672e+12,2.811877e+12,2.855964e+12,2.439189e+12
Iran,12,Middle East,22933,22734,307280,97038,13.40,141,9172000000,119,...,2.662989e+11,3.498816e+11,4.123362e+11,4.163970e+11,4.868076e+11,6.261331e+11,6.440355e+11,4.927756e+11,4.603828e+11,4.082129e+11
Spain,13,Western Europe,21955,21597,352497,64588,16.06,176,4923000000,106,...,1.260399e+12,1.474003e+12,1.631863e+12,1.491473e+12,1.422108e+12,1.480710e+12,1.324751e+12,1.355580e+12,1.371821e+12,1.196157e+12
Brazil,14,Latin America,21524,21236,183915,45172,8.54,127,12149000000,59,...,1.107627e+12,1.397114e+12,1.695855e+12,1.666996e+12,2.208838e+12,2.616157e+12,2.465228e+12,2.472819e+12,2.456044e+12,1.802212e+12
Australia,15,Pacific Region,20614,20147,314307,51583,15.25,176,5386000000,231,...,7.479074e+11,8.544273e+11,1.055686e+12,9.286298e+11,1.148570e+12,1.398456e+12,1.546953e+12,1.576330e+12,1.467590e+12,1.350580e+12

# Questoin 2

In [ ]:
def answer_two():
    years = [str(y) for y in range(2006, 2016)]
    avgGDP = Top15[years].mean(axis=1).sort_values(ascending=False)
    return avgGDP.rename('avgGDP')

answer_two()

Country
United States         1.570403e+13
China                 6.927707e+12
Japan                 5.239642e+12
Germany               3.523342e+12
United Kingdom        2.780276e+12
France                2.691337e+12
Italy                 2.142986e+12
Brazil                1.988889e+12
Russian Federation    1.666746e+12
Canada                1.616359e+12
India                 1.602352e+12
Spain                 1.400886e+12
South Korea           1.221372e+12
Australia             1.207513e+12
Iran                  4.563261e+11
Name: avgGDP, dtype: float64

# Question 3

In [ ]:
def answer_three():
    target_country = answer_two().index[5]
    data = Top15.loc[target_country]
    return data['2015'] - data['2006']

answer_three()

np.float64(118652421857.7959)

# Question 4

In [19]:
def answer_four():
    Top15['Ratio'] = Top15['Self-citations'] / Top15['Citations']
    max_ratio = Top15['Ratio'].max()
    country = Top15['Ratio'].idxmax()
    return (country, max_ratio)

answer_four()

('China', np.float64(0.6912289816173135))

# Question 5

In [ ]:
def answer_five():
    df = Top15.copy()
    df['PopEst'] = df['Energy Supply'] / df['Energy Supply per Capita']
    top3_country = df['PopEst'].sort_values(ascending=False).index[2]
    return str(top3_country)

answer_five()

'United States'

# Question 6

In [ ]:
def answer_six():
    df = Top15.copy()
    df['PopEst'] = df['Energy Supply'] / df['Energy Supply per Capita']
    
    df['Citable docs per Capita'] = df['Citable documents'] / df['PopEst']
    
    correlation = df['Citable docs per Capita'].astype(float).corr(df['Energy Supply per Capita'].astype(float))
    return correlation

answer_six()

np.float64(0.7434709127726777)

# Questoin 7

In [ ]:
def answer_seven():
    ContinentDict  = {'China':'Asia', 'United States':'North America', 'Japan':'Asia', 
                      'United Kingdom':'Europe', 'Russian Federation':'Europe', 'Canada':'North America', 
                      'Germany':'Europe', 'India':'Asia', 'France':'Europe', 'South Korea':'Asia', 
                      'Italy':'Europe', 'Spain':'Europe', 'Iran':'Asia', 'Australia':'Australia', 
                      'Brazil':'South America'}
    
    df = Top15.copy()

    df['PopEst'] = (df['Energy Supply'] / df['Energy Supply per Capita']).astype(float)
    
    df['Continent'] = df.index.to_series().map(ContinentDict)
    
    ans = df.groupby('Continent')['PopEst'].agg(['size', 'sum', 'mean', 'std'])
    
    return ans

answer_seven()

               size           sum          mean           std
Continent
Asia              5  2.898666e+09  5.797333e+08  6.790979e+08
Australia         1  2.331602e+07  2.331602e+07           NaN
Europe            6  4.579297e+08  7.632161e+07  3.464767e+07
North America     2  3.528552e+08  1.764276e+08  1.996696e+08
South America     1  2.059153e+08  2.059153e+08           NaN